# Generated by Django 4.2.3 on 2023-08-11 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0002_alter_cuisine_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0003_alter_restaurant_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="availability",
                        serialize=False,
                        to="restaurant.restaurant",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(1, "Close"), (2, "Open")], default=1),
                ),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[(1, "Not Available"), (2, "Available")], default=1
                    ),
                ),
                ("last_modified_order_status", models.DateTimeField(null=True)),
                (
                    "cancellation",
                    models.IntegerField(
                        choices=[(1, "Not Available"), (2, "Available")], default=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("cuisines", models.ManyToManyField(to="collection.cuisine")),
                ("schedules", models.ManyToManyField(to="collection.schedule")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "availability",
            },
        ),
    ]
