# Generated by Django 4.2.3 on 2023-08-16 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_restaurant_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodCategory",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
