# Generated by Django 4.2.3 on 2023-08-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_alter_restaurant_user"),
        (
            "category",
            "0002_rename_foodcategory_category_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["priority"]},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="category",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categories",
                to="restaurant.restaurant",
            ),
        ),
    ]
