# Generated by Django 4.2.3 on 2023-08-09 11:41

import apps.restaurant.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_restaurant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="restaurant/default.jpg",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                upload_to=apps.restaurant.models.path_and_rename,
            ),
        ),
    ]
