# Generated by Django 4.2.3 on 2023-08-08 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cuisine",
            options={"ordering": ["name"]},
        ),
    ]
