# Generated by Django 4.2.3 on 2023-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businesshour",
            options={"ordering": ["day"]},
        ),
        migrations.AlterField(
            model_name="holidayhour",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="specialofferhour",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
